### ISSUE TITLE
READMEについて

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#2]
以下を削除。

https://github.com/SatoruOokita/example-app/blob/39122641e9ea5526525ba555e24d37d13219f22b/README.md?plain=1#L3-L19

## 解説
GitHubのヘルプページに [READMEについて - GitHub Docs](https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) というものがあり、 *GitHubリポジトリにおけるREADMEの目的・位置付けについて* 説明されています。

で、当該ページに「README ファイルの自動生成された目次」という項があり、GitHubの仕様として目次は自動生成が行われるため、元のファイルに自分で目次を記載する必要はありません。

MS Wordでも「見出し」目安に後から目次を自動生成するのとやってることは同じ。
「Wordはユーザー任意で目次の有無や位置が出力できる」「Markdownは目次の有無や位置はMarkdownの実装依存で決まる」くらいの違い。

## 補足

READMEとして記述する書式としてMarkdown(`.md`)というテキストフォーマットがありますが、さまざまな派生実装がありGitHubではGitHub Flavored Markdown(略称:GFM)が利用可能です。

GitHubでのMarkdownの場合
- [A formal spec for GitHub Flavored Markdown | The GitHub Blog](https://github.blog/2017-03-14-a-formal-spec-for-github-markdown/)
- [GitHub Flavored Markdown Spec](https://github.github.com/gfm/)

また、他のMarkdown実装では以下のものがあるかと思います。
これらもそれぞれの実装で目次を出力することができます。

RedmineでのMarkdownの場合
- [RedmineWikiFormatting (Markdown)](https://tokui-mash.com/redmine/help/ja/wiki_syntax_detailed_markdown.html)

Visual Studio CodeでのMarkdownの場合
- [Markdown editing with Visual Studio Code](https://code.visualstudio.com/Docs/languages/markdown#_common-questions)
- [CommonMark](https://commonmark.org/)

**Comment by SatoruOokita** [comment]
ReadMeの修正を行いました。
1. 以下を削除
https://github.com/SatoruOokita/example-app/blob/39122641e9ea5526525ba555e24d37d13219f22b/README.md?plain=1#L3-L19

2. 誤字脱字なども修正しました。
