### ISSUE TITLE
READMEの修正

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#21]
## 解決済みの課題に対するフィードバックの反映
注意に記載されていた既知の問題が解消されているのであれば、取消線で消す、削除するなどの編集も併せて行う。
https://github.com/SatoruOokita/example-app/blob/main/README.md?plain=1#L10-L12

## 「インストール作業」の前に

```
git clone https://github.com/SatoruOokita/example-app.git
cd example-app
cp .env.example .env
php ./vendor/bin/sail up
php ./vendor/bin/sail composer insall
  :
  :
```
のように開発者が動かせる開発環境としての説明を踏まえて「Vagrantで実行する場合」としてインストール作業の説明をする流れが望ましい。
https://github.com/SatoruOokita/example-app/blob/main/README.md?plain=1#L14

また、ざっくりと「ここ(Vagrantで実行する場合)ではLaravelアプリケーション名は `example-app` とし、デプロイ先を `/var/www/html/example-app` とする」といった概要を記載しておくと、nginxのconfファイルやディレクトリをコピーするくだりが理解しやすくなる。

## example-app のコピー
コピーしてリネームして、という形になっている。
```
cp -r /vagrant /var/www/html/example-app
```
で済ませる。

## 「8. アプリケーション(example-app)をnginxのドキュメンルートへ配置する」
厳密には `example-app/public` が nginx のドキュメントルートなので誤り。
また順序としては、「nginxの設定の記述に合わせてファイルをコピー」より「ファイルのある場所に合わせてnginxの設定ファイルに記述」の方が良い。

## .env ファイルの編集の説明
> 19行目から25行目にコメントアウトしています。 そのコメントアウトを解除した後、11行目から17行目に書いている開発環境における

行番号を当てにしてはいけない。(何かで.envに項目が追加され行番号がずれた場合はREADMEまで編集しなければならない、という手間が発生する)

## .envファイルmysql分の編集とmailhog分の編集
同じファイルを編集するので、間を空けない。

## sudo -u www-data php artisan db:seed でエラー
```
sudo -u www-data php artisan db:seed

   INFO  Seeding database.  

  Database\Seeders\UsersSeeder ................................................................................ RUNNING  

In DatabaseServiceProvider.php line 93:
                                   
  Class "Faker\Factory" not found  
```

`Faker/Factory` は `fakerphp/faker` パッケージに含まれるクラスで、 `composer.json` では `required-dev` に含まれています(なので、`composer insall --no-dev` ではインストールされない)。

対応としてはおおよそ以下のいずれか。
- `artisan db:seed` はあくまで開発環境での初期データとして用意されたものとして、本番環境ではちゃんとしたデータを用意し別途投入する
- 本番環境でも使いたい

## ブラウザでアクセスするなら
URLで表現した方が都合が良い。

http://192.168.56.56:8025
https://github.com/SatoruOokita/example-app/blob/main/README.md?plain=1#L301-L303

http://192.168.56.56
https://github.com/SatoruOokita/example-app/blob/main/README.md?plain=1#L308-L310

**Comment by SatoruOokita** [comment]
ありがとうございます。
修正していきます。

**Comment by SatoruOokita** [comment]
@ken-taniguchi 
ReadMeを修正しました。

ReadMeの変更に伴い`composer.json`の内容を修正し、開発環境で`composer update`コマンドを実行して、`composer.lock`ファイルの内容を更新しています。
