### ISSUE TITLE
別途Vagrant用にディレクトリを用意しない場合について

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#4]
https://github.com/SatoruOokita/example-app/blob/3d4d1ab0a5f977f35e61ebbfefbb64b45def28b0/README.md?plain=1#L28-L30

別途ディレクトリを作ることなくプロジェクト直下で `vagrant up` する方法が一般的です。
この場合の手順はどうなりますか？

**Comment by SatoruOokita** [comment]
プロジェクト直下で vagrant up する方法が一般的なのですね。
その方法は考えていなかったのでこれから手順を調べます。
