### ISSUE TITLE
sudo composer install について

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#5]
https://github.com/SatoruOokita/example-app/blob/3d4d1ab0a5f977f35e61ebbfefbb64b45def28b0/README.md?plain=1#L209

```
sudo composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
```
という警告が出ているはずです。
※ https://getcomposer.org/root を参照すると、rootユーザで実行させないことを強く勧めている理由が記載されています。
当該プロジェクトでは、ファイル、ディレクトリの所有者を `www-data` としたので `sudo` コマンドでユーザーを変更するオプションを指定しましょう。

また、デプロイ先として本番環境を想定しているので、開発環境で必要とされているライブラリ(`composer.json` の `require-dev` に記載)は必要ありません。`composer install` で開発用ライブラリを除外するオプションを指定しましょう。
https://getcomposer.org/doc/03-cli.md#install-i

まとめ
`sudo -u www-data composer install --no-dev`

**Comment by ken-taniguchi** [comment]
追記: [Deployment - Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/9.x/deployment#autoloader-optimization) によれば、オートローダの最適化も行うとのことで、手順が示されています。
確認しましょう。

**Comment by SatoruOokita** [comment]
@ken-taniguchi 
`sudo composer install`としていた部分を`sudo -u www-data composer install --optimize-autoloader --no-dev`に変更しています。

https://getcomposer.org/doc/03-cli.md#install-i には`--optimize-autoloader`オプションは現在デフォルトでは実行されないとあったのですが、追記してくださっていた[Deployment - Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/9.x/deployment#autoloader-optimization)では、推奨されていたので付け足しています。


> --optimize-autoloader (-o): Convert PSR-0/4 autoloading to classmap to get a faster autoloader. This is recommended especially for production, but can take a bit of time to run, so it is currently not done by default.
>（日本語訳:DeepL）
>--optimize-autoloader (-o)： PSR-0/4のオートローディングをclasmapに変換して、より高速なオートローダを得る。これは特にプロダクションで推奨されますが、実行に少し時間がかかるので、現在デフォルトでは実行されません。
>
>https://getcomposer.org/doc/03-cli.md#install-i のページから抜粋

**Comment by ken-taniguchi** [comment]
@SatoruOokita 
> https://getcomposer.org/doc/03-cli.md#install-i には--optimize-autoloaderオプションは現在デフォルトでは実行されないとあったのですが、追記してくださっていた[Deployment - Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/9.x/deployment#autoloader-optimization)では、推奨されていたので付け足しています。

表現が掴みかねるのであとで確認。

**Comment by SatoruOokita** [comment]
申し訳ありません。
自分の理解が不十分なまま、作業の報告をしてしまいました。推敲もきちんとできていませんでした。

調べたり、GPTに聞いたりすることで、`--optimize-autoloader`オプションはオートローダーのパフォーマンスを向上させるために本番環境で推奨されるオプションだということが分かりました。

今回のReadMeでは本番環境にデプロイする手順を示しているので、本番環境で推奨されている`--optimize-autoloader`オプションを`composer install`に付け足しています。
