### ISSUE TITLE
en, ja フォルダについて

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#6]
- en/
- ja/
- lang/en/
- lang/ja/

にロケール別の文言リソースが記載されているように見えるが、すべて必要か？

**Comment by SatoruOokita** [comment]
多言語化を進める予定はないので整理します。
ブランチを切り、

- en/
- lang/em/

の2つを削除してプルリクエストを作成させていただきます。

**Comment by ken-taniguchi** [comment]
@SatoruOokita そうではなく、多言語化するフォルダ構成として `lang` ディレクトリ以下に構成することになっているはずです。
参考: [Localization - Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/9.x/localization)

なので、プロジェクトディレクトリ直下の `en/`, `ja/` が **配置先として誤っている** ということです。

**Comment by SatoruOokita** [comment]
ありがとうございます。
谷口さんの指摘を理解できていませんでした。
ドキュメントを読んでおきます。

**Comment by SatoruOokita** [comment]
学習に用いたテキストとドキュメントを読みました。
langディレクトリ下にen/やja/を置くと書いていました。
