### ISSUE TITLE
メール送信機能をテストするための環境を整えること

### ISSUE THREAD

**Issue by ken-taniguchi** [SatoruOokita/example-app#9]
> ※ Mailhogのインストールができていないため、会員登録を行うとエラー画面になります。

**Comment by SatoruOokita** [comment]
これからこちらのイシューの対応を始めます。
まずは公式のドキュメントからリサーチを開始していきます。

https://readouble.com/laravel/9.x/ja/mail.html

**Comment by SatoruOokita** [comment]
@ken-taniguchi 
お疲れ様です。
Mailhogの機能を有効にできたので、これからMailgunのAPIを利用する方法を試します。

Mailgunでメールの送信と受信が出来たにせよ、出来なかったにせよ、ReadMeには`Mailhog`を有効にする手順を書き足し、VagrantfileにもMailhogをインストールする記述を付け足そうと考えています。

作業の方針に誤りはないでしょうか？
すみませんがよろしくお願いいたします。

**Comment by SatoruOokita** [comment]
@ken-taniguchi 
お疲れ様です。
ReadMeにMailhogをインストールし、メールが送信できているかを確かめる手順を書き足しました。

こちらの手順で再度リポジトリのクローンからやり直し、メールの送信までの作業を完了できました。
